### ISSUE TITLE
Issue in Rmpq_z_div(r, z, q) when z=0

### ISSUE THREAD

**Issue by trizen** [sisyphus/math-gmpq#3]
Hi Rob,

There is a minor issue in `Rmpq_z_div(r, z, q)` when `z` holds the value `0`.

```perl
use strict;
use warnings;

use Math::GMPz;
use Math::GMPq;

my $r = Math::GMPq->new('0');
my $z = Math::GMPz->new('0');
my $q = Math::GMPq->new('42');

Math::GMPq::Rmpq_z_div($r, $z, $q);

print $r;                        # should print '0'
```

Output:
```
[1]    31405 floating point exception (core dumped)  perl x.pl
```

**Comment by sisyphus** [comment]
From: Daniel Șuteu
Sent: Monday, April 17, 2017 9:31 AM
To: sisyphus/math-gmpq
Cc: Subscribed
Subject: [sisyphus/math-gmpq] Issue in Rmpq_z_div(r, z, q) when z=0 (#3)

Hi Rob,

> There is a minor issue in Rmpq_z_div(r, z, q) when the z holds the value 
> 0.

Duh ... probably shouldn't multiply a denominator by zero.

I think (untested) this will work correctly:

void Rmpq_z_div(mpq_t * rop, mpz_t * z, mpq_t * op) {
     if(rop != op) mpq_set(*rop, *op);
     mpq_inv(*rop, *rop);
     mpz_mul(mpq_numref(*rop), mpq_numref(*rop), *z);
     mpq_canonicalize(*rop);
}

But I also need to catch the "divide-by-zero" cases - in many (if not all) 
of the division routines.

The ones I tested all crash on "divide-by-zero" which is not very helpful.
I expect that the above reworking of Rmpq_z_div will also crash if op is 
zero, irrespective of the value of z.

I just need to insert code that calls a croak() whenever a "divide-by-zero" 
is about to occur.

I'll do that over the next couple of days, write some tests that check that 
"divide-by-zero" is being caught, and then push another release to CPAN.

Cheers,
Rob

**Comment by sisyphus** [comment]
I've just pushed Math-GMPq-0.45 to CPAN.
Hopefully this fixes the issue (along with the divby0 issues I mentioned above).
Cheers,
Rob

**Comment by trizen** [comment]
Hi Rob,

Fix confirmed here. Thank you very much.

Regards,
Daniel
